//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int DecodeHeight {
            get {
                return ((int)(this["DecodeHeight"]));
            }
            set {
                this["DecodeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double GünlükGecikmeBedeli {
            get {
                return ((double)(this["GünlükGecikmeBedeli"]));
            }
            set {
                this["GünlükGecikmeBedeli"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double HızlıKitapGirişGünSüresi {
            get {
                return ((double)(this["HızlıKitapGirişGünSüresi"]));
            }
            set {
                this["HızlıKitapGirişGünSüresi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Aktarma {
            get {
                return ((bool)(this["Aktarma"]));
            }
            set {
                this["Aktarma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KitapResimGöster {
            get {
                return ((bool)(this["KitapResimGöster"]));
            }
            set {
                this["KitapResimGöster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KişiGirişEkranıVarsayılan {
            get {
                return ((bool)(this["KişiGirişEkranıVarsayılan"]));
            }
            set {
                this["KişiGirişEkranıVarsayılan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double YaklaşanİşlemlerGünSayısı {
            get {
                return ((double)(this["YaklaşanİşlemlerGünSayısı"]));
            }
            set {
                this["YaklaşanİşlemlerGünSayısı"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QrMultipleBorderThickness {
            get {
                return ((double)(this["QrMultipleBorderThickness"]));
            }
            set {
                this["QrMultipleBorderThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MaksimumUzatmaSayısı {
            get {
                return ((int)(this["MaksimumUzatmaSayısı"]));
            }
            set {
                this["MaksimumUzatmaSayısı"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KişiResimGöster {
            get {
                return ((bool)(this["KişiResimGöster"]));
            }
            set {
                this["KişiResimGöster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OtomatikTutanak {
            get {
                return ((bool)(this["OtomatikTutanak"]));
            }
            set {
                this["OtomatikTutanak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double KişiKitapKritikOran {
            get {
                return ((double)(this["KişiKitapKritikOran"]));
            }
            set {
                this["KişiKitapKritikOran"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SeçiliTts {
            get {
                return ((string)(this["SeçiliTts"]));
            }
            set {
                this["SeçiliTts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KimlikArkaPlanResim {
            get {
                return ((string)(this["KimlikArkaPlanResim"]));
            }
            set {
                this["KimlikArkaPlanResim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KişiKitapKritikKontrol {
            get {
                return ((bool)(this["KişiKitapKritikKontrol"]));
            }
            set {
                this["KişiKitapKritikKontrol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KurumAdı {
            get {
                return ((string)(this["KurumAdı"]));
            }
            set {
                this["KurumAdı"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double KimlikArkaPlanResimŞeffaflık {
            get {
                return ((double)(this["KimlikArkaPlanResimŞeffaflık"]));
            }
            set {
                this["KimlikArkaPlanResimŞeffaflık"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResimKüçült {
            get {
                return ((bool)(this["ResimKüçült"]));
            }
            set {
                this["ResimKüçült"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double ResimKüçültmeOranı {
            get {
                return ((double)(this["ResimKüçültmeOranı"]));
            }
            set {
                this["ResimKüçültmeOranı"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KitapVermeİşGünüSay {
            get {
                return ((bool)(this["KitapVermeİşGünüSay"]));
            }
            set {
                this["KitapVermeİşGünüSay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OtomatikYedek {
            get {
                return ((bool)(this["OtomatikYedek"]));
            }
            set {
                this["OtomatikYedek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int EskiYedekGün {
            get {
                return ((int)(this["EskiYedekGün"]));
            }
            set {
                this["EskiYedekGün"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bu Kimlik Kaybolursa İlgili İdareye Teslim Edin.")]
        public string KimlikNotu {
            get {
                return ((string)(this["KimlikNotu"]));
            }
            set {
                this["KimlikNotu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CODE_128")]
        public global::ZXing.BarcodeFormat SeçiliBarkod {
            get {
                return ((global::ZXing.BarcodeFormat)(this["SeçiliBarkod"]));
            }
            set {
                this["SeçiliBarkod"] = value;
            }
        }
    }
}
